### ISSUE TITLE
 firefox and xpra enabling GUI

### ISSUE THREAD

**Issue by babacoders** [retog/docker-x11-xpra#3]
Is it possible to run firefox on one Docker container and xpra in a seperate container and then using boht to make GUI work?

**Comment by retog** [comment]
That's not something I've tried but I don't see why not. Something like

    ssh -p 2020 user@localhost "ssh -X othercontainer firefox"

**Comment by babacoders** [comment]
I tried  https://github.com/dockerworxinc/xpra-firefox

Does it look feasible?
I got a single docker container working which includes both Xpra and
Firefox. But want to achieve it through docker compose or two containers
linked to each other.

Do suggest.

**Comment by retog** [comment]
Why shouldn't it work? in your docker-compose the port of the container with xpra is exposed, you connect to that port on localhost and from there you connect to the firefox container using the name it has in the docker-compose, as with the command I suggested above.

You may need/want to set the authorized keys to allow password-free access from the xpra container to the firefox container.

**Comment by dockerworxinc** [comment]
Thanks. This is what I came up with.

```
version: '2'

services:

  x11-bridge:
    image: jare/x11-bridge
    container_name: x11-bridge
    environment:
      MODE: "tcp"
      XPRA_HTML: "yes"
      DISPLAY: ":14"
    port:
      - "10000:10000"
  
  firefox:
    image: sassman/debian-firefox
    container_name: firefox
    environment:
      DISPLAY: ":14"
    volumes_from:
      - x11-bridge:rw
    command: /bin/bash -c "/usr/bin/firefox"
```

**Comment by dockerworxinc** [comment]
Looks to be some issue with firefox

```
docker-compose up
Creating firefox ... done
Creating firefox ... 
Attaching to x11-bridge, firefox
x11-bridge    | Starting in the tcp mode.
x11-bridge    | 
x11-bridge    | X.Org X Server 1.19.3
x11-bridge    | Release Date: 2017-03-15
x11-bridge    | X Protocol Version 11, Revision 0
x11-bridge    | Build Operating System: Linux 4.4.45-0-grsec x86_64 
x11-bridge    | Current Operating System: Linux c0cd1549af8d 4.13.0-36-generic #40-Ubuntu SMP Fri Fe
b 16 20:07:48 UTC 2018 x86_64
x11-bridge    | Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.13.0-36-generic root=LABEL=cloudimg-
rootfs ro scsi_mod.use_blk_mq=Y console=ttyS0
x11-bridge    | Build Date: 23 May 2017  03:46:32PM
x11-bridge    |  
x11-bridge    | Current version of pixman: 0.34.0
x11-bridge    |         Before reporting problems, check http://wiki.x.org
x11-bridge    |         to make sure that you have the latest version.
x11-bridge    | Markers: (--) probed, (**) from config file, (==) default setting,
x11-bridge    |         (++) from command line, (!!) notice, (II) informational,
x11-bridge    |         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
x11-bridge    | (++) Log file: "/tmp/Xorg.log", Time: Sat Mar 10 12:54:57 2018
x11-bridge    | (++) Using config file: "/etc/xpra/xorg.conf"
x11-bridge    | (==) Using config directory: "/etc/X11/xorg.conf.d"
x11-bridge    | (==) Using system config directory "/usr/share/X11/xorg.conf.d"
x11-bridge    | 
x11-bridge    | X.Org X Server 1.19.3
x11-bridge    | ** (process:19): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum whe
n in fact it is of type 'GFlags'
x11-bridge    | 
x11-bridge    | ** (process:19): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when
 in fact it is of type 'GFlags'
x11-bridge    | 2018-03-10 12:55:00,457 created unix domain socket: /home/xpra/.xpra/c0cd1549af8d-14
x11-bridge    | 2018-03-10 12:55:00,458 created unix domain socket: /var/run/xpra/c0cd1549af8d-14
x11-bridge    | 2018-03-10 12:55:10,390 serving html content from: /usr/share/xpra/www
x11-bridge    | 2018-03-10 12:55:10,484 D-Bus notification forwarding is available
x11-bridge    | 2018-03-10 12:55:10,622 3.6GB of system memory
x11-bridge    | 2018-03-10 12:55:11,142 started command 'xhost +' with pid 47
x11-bridge    | 2018-03-10 12:55:11,143 xpra X11 version 2.0.1-r15494 64-bit
x11-bridge    | 2018-03-10 12:55:11,144  uid=1000 (xpra), gid=1000 (xpra)
x11-bridge    | 2018-03-10 12:55:11,144  running with pid 19 on Linux
x11-bridge    | 2018-03-10 12:55:11,144  connected to X11 display :14 with 24 bit colors
x11-bridge    | access control disabled, clients can connect from any host
x11-bridge    | 2018-03-10 12:55:11,404 child 'xhost +' with pid 47 has terminated
x11-bridge    | 2018-03-10 12:55:11,404 xpra is ready.
firefox       | ExceptionHandler::GenerateDump cloned child 90
firefox       | ExceptionHandler::SendContinueSignalToChild sent continue signal to child
firefox       | ExceptionHandler::WaitForContinueSignal waiting for continue signal...
firefox       | 2018-03-10 12:55:36: minidump.cc:4808: ERROR: ReadBytes: read 0/32
firefox       | 2018-03-10 12:55:36: minidump.cc:4453: ERROR: Minidump cannot read header
firefox exited with code 135
```

**Comment by dockerworxinc** [comment]
Can you help me with SSH example which you talked about?

**Comment by babacoders** [comment]
volume_from is an option for v2 files. It's not supported in v3 because the option isn't swarm-compatible. Hence, I came up with the below example:

```
version: '2'

services:

  x11-bridge:
    image: jare/x11-bridge
    network_mode: host
    #container_name: x11-bridge
    environment:
      MODE: "tcp"
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_PASSWORD: 111
    port:
      - "10000:10000"
  
  firefox:
    image: sassmann/debian-firefox
    #container_name: firefox
     depends_on:
         - x11-display
    network_mode: host
    environment:
      DISPLAY: ":14"
    volumes_from:
      - x11-bridge
    command: /bin/bash -c "/usr/bin/firefox"
```


Looks to be some issue with firefox

docker-compose up
Creating firefox ... done
Creating firefox ... 
Attaching to x11-bridge, firefox
x11-bridge    | Starting in the tcp mode.
x11-bridge    | 
x11-bridge    | X.Org X Server 1.19.3
x11-bridge    | Release Date: 2017-03-15
x11-bridge    | X Protocol Version 11, Revision 0
x11-bridge    | Build Operating System: Linux 4.4.45-0-grsec x86_64 
x11-bridge    | Current Operating System: Linux c0cd1549af8d 4.13.0-36-generic #40-Ubuntu SMP Fri Fe
b 16 20:07:48 UTC 2018 x86_64
x11-bridge    | Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.13.0-36-generic root=LABEL=cloudimg-
rootfs ro scsi_mod.use_blk_mq=Y console=ttyS0
x11-bridge    | Build Date: 23 May 2017  03:46:32PM
x11-bridge    |  
x11-bridge    | Current version of pixman: 0.34.0
x11-bridge    |         Before reporting problems, check http://wiki.x.org
x11-bridge    |         to make sure that you have the latest version.
x11-bridge    | Markers: (--) probed, (**) from config file, (==) default setting,
x11-bridge    |         (++) from command line, (!!) notice, (II) informational,
x11-bridge    |         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
x11-bridge    | (++) Log file: "/tmp/Xorg.log", Time: Sat Mar 10 12:54:57 2018
x11-bridge    | (++) Using config file: "/etc/xpra/xorg.conf"
x11-bridge    | (==) Using config directory: "/etc/X11/xorg.conf.d"
x11-bridge    | (==) Using system config directory "/usr/share/X11/xorg.conf.d"
x11-bridge    | 
x11-bridge    | X.Org X Server 1.19.3
x11-bridge    | ** (process:19): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum whe
n in fact it is of type 'GFlags'
x11-bridge    | 
x11-bridge    | ** (process:19): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when
 in fact it is of type 'GFlags'
x11-bridge    | 2018-03-10 12:55:00,457 created unix domain socket: /home/xpra/.xpra/c0cd1549af8d-14
x11-bridge    | 2018-03-10 12:55:00,458 created unix domain socket: /var/run/xpra/c0cd1549af8d-14
x11-bridge    | 2018-03-10 12:55:10,390 serving html content from: /usr/share/xpra/www
x11-bridge    | 2018-03-10 12:55:10,484 D-Bus notification forwarding is available
x11-bridge    | 2018-03-10 12:55:10,622 3.6GB of system memory
x11-bridge    | 2018-03-10 12:55:11,142 started command 'xhost +' with pid 47
x11-bridge    | 2018-03-10 12:55:11,143 xpra X11 version 2.0.1-r15494 64-bit
x11-bridge    | 2018-03-10 12:55:11,144  uid=1000 (xpra), gid=1000 (xpra)
x11-bridge    | 2018-03-10 12:55:11,144  running with pid 19 on Linux
x11-bridge    | 2018-03-10 12:55:11,144  connected to X11 display :14 with 24 bit colors
x11-bridge    | access control disabled, clients can connect from any host
x11-bridge    | 2018-03-10 12:55:11,404 child 'xhost +' with pid 47 has terminated
x11-bridge    | 2018-03-10 12:55:11,404 xpra is ready.
firefox       | ExceptionHandler::GenerateDump cloned child 90
firefox       | ExceptionHandler::SendContinueSignalToChild sent continue signal to child
firefox       | ExceptionHandler::WaitForContinueSignal waiting for continue signal...
firefox       | 2018-03-10 12:55:36: minidump.cc:4808: ERROR: ReadBytes: read 0/32
firefox       | 2018-03-10 12:55:36: minidump.cc:4453: ERROR: Minidump cannot read header
firefox exited with code 135

```
